name: Trigger auto deployment for internal-voice-agent

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/internal-voice-agent-AutoDeployTrigger-3cf153fc-5e5b-441a-8ba0-a8dafa69ca77.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Create credentials from secrets
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json
          echo "✅ Created credentials.json"

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.INTERNALVOICEAGENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.INTERNALVOICEAGENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.INTERNALVOICEAGENT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ailifebotregistry.azurecr.io
          registryUsername: ${{ secrets.INTERNALVOICEAGENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.INTERNALVOICEAGENT_REGISTRY_PASSWORD }}
          containerAppName: internal-voice-agent
          resourceGroup: rg-sample-lab
          imageToBuild: ailifebotregistry.azurecr.io/internal-voice-agent:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


